// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0rYnJPJAzy6t-L-5X6hVU6E3AXo-C2o',
    appId: '1:936878521640:web:7f5d674d2bf333bbd1641d',
    messagingSenderId: '936878521640',
    projectId: 'zaqapp-39377',
    authDomain: 'zaqapp-39377.firebaseapp.com',
    storageBucket: 'zaqapp-39377.firebasestorage.app',
    measurementId: 'G-4S2C0TKDTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMRjCnVXk6sj3PFT8M0sp9l-qU3yn2UM',
    appId: '1:936878521640:android:5468297cc7ff18fed1641d',
    messagingSenderId: '936878521640',
    projectId: 'zaqapp-39377',
    storageBucket: 'zaqapp-39377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc8OTEL4gQYOCU5AVIfvyT4NwOEhGf3VI',
    appId: '1:936878521640:ios:4592aa5f7d42d750d1641d',
    messagingSenderId: '936878521640',
    projectId: 'zaqapp-39377',
    storageBucket: 'zaqapp-39377.firebasestorage.app',
    iosBundleId: 'com.example.zaqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc8OTEL4gQYOCU5AVIfvyT4NwOEhGf3VI',
    appId: '1:936878521640:ios:4592aa5f7d42d750d1641d',
    messagingSenderId: '936878521640',
    projectId: 'zaqapp-39377',
    storageBucket: 'zaqapp-39377.firebasestorage.app',
    iosBundleId: 'com.example.zaqapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ0rYnJPJAzy6t-L-5X6hVU6E3AXo-C2o',
    appId: '1:936878521640:web:aaa2b132cbe96063d1641d',
    messagingSenderId: '936878521640',
    projectId: 'zaqapp-39377',
    authDomain: 'zaqapp-39377.firebaseapp.com',
    storageBucket: 'zaqapp-39377.firebasestorage.app',
    measurementId: 'G-669X5BSGK1',
  );
}
